'use strict';

export const diePrying = [
  {
    name: 'Tissiana Alves',
    website: null,
    email: null,
    github: null,
    linkedin: null,
    medium: null,
  },
  {
    name: 'Lillian Bitner',
    website: null,
    email: 'lillian.bitner@gmail.com',
    github: 'https://github.com/lilbitner',
    linkedin: 'https://www.linkedin.com/in/lillian-bitner/',
    medium: null,
  },
  {
    name: 'Aaron Burmeister',
    website: 'https://aaronburmeister.tech/',
    email: 'aaronburmeister91@gmail.com',
    github: 'https://github.com/aaronburmeister',
    linkedin: 'https://www.linkedin.com/in/aaronburmeister/',
    medium: 'https://medium.com/@aaronburmeister',
  },
  {
    name: 'Josh Cabral',
    website: null,
    email: null,
    github: 'https://github.com/joshycsm',
    linkedin: 'https://www.linkedin.com/in/joshycsm/',
    medium: 'https://joshycsm.medium.com/',
  },
  {
    name: 'Miwha Geschwind',
    website: 'https://miwha.co/',
    email: 'miwha.geschwind@gmail.com',
    github: 'https://github.com/miwhag',
    linkedin: 'https://www.linkedin.com/in/miwha-geschwind/',
    medium: 'https://medium.com/@miwhag',
  },
  {
    name: 'Jeremy Gray',
    website: null,
    email: 'jeremytgray6@gmail.com',
    github: 'https://github.com/jtgray6',
    linkedin: 'https://www.linkedin.com/in/jeremytgray6/',
    medium: null,
  },
  {
    name: 'Evan Greer',
    website: 'https://www.evan-greer.co/',
    email: 'etgreer91@gmail.com',
    github: 'https://github.com/evantk91',
    linkedin: 'https://www.linkedin.com/in/evantk91/',
    medium: 'https://etgreer91.medium.com/',
  },
  {
    name: 'Bradley Haley',
    website: null,
    email: 'Bshaley25@gmail.com',
    github: 'https://github.com/bshaley25',
    linkedin: 'https://www.linkedin.com/in/bradley-haley-44a85b19a/',
    medium: null,
  },
  {
    name: 'Corey Hodge',
    website: 'https://coreyhodge.net/',
    email: 'contact@coreyhodge.net',
    github: 'https://github.com/WordsPerMinute',
    linkedin: 'https://www.linkedin.com/in/coreyhodge/',
    medium: 'https://medium.com/@coreyhodgedotnet',
  },
  {
    name: 'Douglas Johnson',
    website: 'https://dougj.dev/',
    email: 'doug@dougj.dev',
    github: 'https://github.com/Douglas-J-Johnson',
    linkedin: 'https://www.linkedin.com/in/douglas-j-johnson/',
    medium: null,
    // blogger: 'https://blog.dougj.dev/',
  },
  {
    name: 'Jared Matta',
    website: 'https://jared-matta.web.app/',
    email: 'cherokeedreemer@gmail.com',
    github: 'https://github.com/AlteredArt',
    linkedin: 'https://www.linkedin.com/in/jared-matta/',
    medium: 'https://cherokeedreemer.medium.com/',
    // twitter: 'https://twitter.com/jared_matta',
  },
  {
    name: 'Michael Newman',
    website: null,
    email: null,
    github: 'https://github.com/coloradohokie',
    linkedin: 'https://www.linkedin.com/in/michael-newman-denver/',
    medium: null,
  },
  {
    name: 'Jorge Santos',
    website: 'https://jorgesantos-38e0a.firebaseapp.com/',
    email: 'Jlsantos280@gmail.com',
    github: 'https://github.com/Jsantos107',
    linkedin: 'https://www.linkedin.com/in/santos-jorge/',
    medium: 'https://medium.com/@JorgeSantos7',
  },
  {
    name: 'Adam Shappy',
    website: 'https://adam-shappy.com/',
    email: 'ajs11300@gmail.com',
    github: 'https://github.com/mrshappy0',
    linkedin: 'https://www.linkedin.com/in/adam-shappy/',
    medium: 'https://medium.com/@adam_shappy',
  },
];
