'use strict';

export const users = [
  {
    name: 'Raz Al-Jaf',
    website: null,
    email: 'razaljaf@gmail.com',
    github: 'https://github.com/ThatoneKurdishSE',
    linkedin: 'https://www.linkedin.com/in/razaljaf/',
    medium: 'https://razaljaf.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Ryan Anderson',
    website: null,
    email: 'ryan.t.anderson19@gmail.com',
    github: null,
    linkedin: null,
    medium: null,
    // cohort: 'Notorious Git 7/9/20',
  },
  {
    name: 'Thomas Bachorz',
    // website: 'https://tjbachorz.live/',
    website: 'tjbachorz.live',
    email: null,
    github: 'https://github.com/TJBachorz',
    linkedin: 'https://www.linkedin.com/in/tjbachorz/',
    medium: 'https://tjbachorz.medium.com/',
    // twitter: 'https://twitter.com/ThomasBachorz',
    // cohort: '',
  },
  {
    name: 'Mell Basham',
    website: null,
    email: 'mellbasham@gmail.com',
    github: 'https://github.com/MellB0501',
    linkedin: 'https://www.linkedin.com/in/mell-basham',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Nyaradzo Bere',
    website: null,
    email: 'nybe5598@colorado.edu',
    github: 'https://github.com/NyaradzoUBere',
    linkedin: 'https://www.linkedin.com/in/nyaradzo-bere/',
    medium: 'https://medium.com/@nyaradzobere',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Brook Beyene',
    // website: 'https://www.wayup.com/profile/Brook-Beyene-744ad6aea7/',
    website: 'wayup.com/profile/Brook-Beyene-744ad6aea7',
    email: 'brookbeyene37@gmail.com',
    github: 'https://github.com/brookbeyene',
    linkedin: 'https://www.linkedin.com/in/bbeyene/',
    medium: null,
  },
  {
    name: 'Gerald Bivens',
    // website: 'https://jamespeirce.com/',
    website: 'jamespeirce.com',
    email: 'geraldbivens@gmail.com',
    github: 'https://github.com/geraldbivens',
    linkedin: 'https://www.linkedin.com/in/gerald-bivens/',
    medium: 'https://medium.com/@geraldbivens',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Javaria Brascom',
    website: null,
    email: 'javariab17@gmail.com',
    github: 'https://github.com/jay719',
    linkedin: 'https://www.linkedin.com/in/javaria-brascom-0510991bb/',
    medium: 'https://javariab17.medium.com/',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Bradley Calkins',
    website: null,
    email: 'b.raders1013@gmail.com',
    github: 'https://github.com/bmcalkins',
    linkedin: 'https://www.linkedin.com/in/bradley-calkins/',
    medium: 'https://bradleycalkins.medium.com/',
    // cohort: '',
  },
  {
    name: 'Damon Chivers',
    // website: 'https://www.damonchivers.com/',
    website: 'damonchivers.com',
    email: null,
    github: 'https://github.com/DamonLC21',
    linkedin: 'https://www.linkedin.com/in/damon-chivers/',
    medium: null,
  },
  {
    name: 'Ryan Choe',
    // website: 'https://ryanachoe.com/',
    website: 'ryanachoe.com',
    email: 'Ryan.Choe@outlook.com',
    github: 'https://github.com/rchoe1229',
    linkedin: 'https://www.linkedin.com/in/ryanchoe1229/',
    medium: 'https://chowderchoe.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Katie Clark',
    // website: 'https://www.katielaelclark.me/',
    website: 'katielaelclark.me',
    email: 'kathrynlael@gmail.com',
    github: 'https://github.com/kathryn0908/',
    linkedin: 'https://www.linkedin.com/in/kathryn-clark-fullstackprogrammer/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kyle Coberly',
    // website: 'https://kylecoberly.com/',
    website: 'kylecoberly.com',
    email: 'kyle.coberly@gmail.com',
    github: 'https://github.com/kylecoberly',
    linkedin: 'https://www.linkedin.com/in/kylecoberly/',
    medium: 'https://medium.com/@kyle.coberly',
  },
  // {
  //   name: 'Cristina Cristobal',
  //   website: null,
  //   email: null,
  //   github: null,
  //   linkedin: null,
  //   medium: 'https://medium.com/@cristicristo',
  // },
  {
    name: 'Nate Croteau',
    website: null,
    email: 'natekcroteau@gmail.com',
    github: 'https://github.com/natekcroteau',
    linkedin: 'https://www.linkedin.com/in/nate-croteau/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Mike De La Rosa',
    website: null,
    email: 'mdelarosa86@gmail.com',
    github: 'https://github.com/mdelarosa',
    linkedin: 'https://www.linkedin.com/in/mdelarosa/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kyle Davis',
    website: null,
    email: 'davis.h.kyle@gmail.com',
    github: 'https://github.com/harland-davis',
    linkedin: 'https://www.linkedin.com/in/kyle-harland-davis',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Jamon Dixon',
    website: null,
    email: 'jamonadixon@gmail.com',
    github: 'https://github.com/Jamondixon',
    linkedin: 'https://www.linkedin.com/in/jamondixon/',
    medium: 'https://jamondixon.medium.com/',
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Hannah Drury',
    website: null,
    email: 'hannahdruryutd@gmail.com',
    github: 'https://github.com/wolf-dominion',
    linkedin: 'https://www.linkedin.com/in/hannah-drury/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kristine Du',
    website: null,
    email: 'kristine.a.du@gmail.com',
    github: 'https://github.com/kadrianne',
    linkedin: 'https://www.linkedin.com/in/kristine-du/',
    medium: 'https://kristine-a-du.medium.com/',
    // cohort: '',
  },
  {
    name: 'Nolan Dyke',
    website: null,
    email: 'nolan.g.dyke@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/nolan-dyke/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Ben Dunn',
    website: null,
    email: 'benthedunn@gmail.com',
    github: 'https://github.com/btdunn',
    linkedin: 'https://www.linkedin.com/in/ben-dunn-15977b15b/',
    medium: 'https://benthedunn.medium.com/',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Nathan Fedzen',
    website: null,
    email: 'nathanfedzen@gmail.com',
    github: 'https://github.com/nfedzen',
    linkedin: 'https://www.linkedin.com/in/nathan-fedzen/',
    medium: null,
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'David Fertitta',
    website: null,
    email: 'davidj.fertitta@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/david-fertitta-99298715b/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Brian Firooz',
    website: null,
    email: 'brianfirooz@mac.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/brian-firooz/',
    medium: null,
    // twitter: 'https://twitter.com/brianfirooz',
  },
  {
    name: 'Chris Follen',
    // website: 'www.chrisfollen.com',
    website: 'chrisfollen.com',
    email: 'christopher.follen@gmail.com',
    github: 'https://github.com/chrisfollen',
    linkedin: 'https://www.linkedin.com/in/chrisfollen/',
    medium: null,
    // email: 'chris@chrisfollen.com',
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Ahmed Gaber',
    website: null,
    email: null,
    github: 'https://github.com/LimitToInfinity',
    linkedin: 'https://www.linkedin.com/in/ahmedtgaber/',
    medium: 'https://medium.com/@21stlimitless',
    // cohort: '',
  },
  {
    name: 'Alexander Gabriel',
    website: null,
    email: 'alexandrgabe@gmail.com',
    github: 'https://github.com/kosmos02',
    linkedin: 'https://www.linkedin.com/in/alexander-m-gabriel/',
    medium: 'https://alexandermgabriel.medium.com/',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'James Giosmas',
    website: null,
    email: 'giosmasj@gmail.com',
    github: 'https://github.com/giosmasj',
    linkedin: 'https://www.linkedin.com/in/james-giosmas/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kevin Glasgow',
    website: null,
    email: 'kglas001@gmail.com',
    github: 'https://github.com/TheRealKevBot',
    linkedin: 'https://www.linkedin.com/in/kevin-glasgow/',
    medium: 'https://real-kevbot.medium.com/',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Sam Gold',
    website: null,
    email: 'samgolddev@gmail.com',
    github: 'https://github.com/sgold57',
    linkedin: 'https://www.linkedin.com/in/samgold57/',
    medium: null,
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Jeff Golden',
    // website: 'https://gjeffgolden.com/',
    website: 'gjeffgolden.com',
    email: 'codebygolden@gmail.com',
    github: 'https://github.com/gjeffgolden',
    linkedin: 'https://www.linkedin.com/in/gjeffgolden/',
    medium: null,
    // blogger: 'http://gjeffgolden.blogspot.com/',
    // twitter: 'https://twitter.com/GJeffGolden',
    // email: 'gjgolden08@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Nick Gray',
    website: null,
    email: 'nickgray87@gmail.com',
    github: 'https://github.com/nickgray06',
    linkedin: 'https://www.linkedin.com/in/nick-gray-06/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Lydia Gregory',
    // website: 'https://lydiagregory.dev/',
    website: 'lydiagregory.dev',
    email: 'lydia.gregory.dev@gmail.com',
    github: 'https://github.com/ljg2gb',
    linkedin: 'https://www.linkedin.com/in/lydia-gregory/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Nathan Gusky',
    website: null,
    email: 'nathangusky13@gmail.com',
    github: 'https://github.com/Guskyn13',
    linkedin: 'https://www.linkedin.com/in/nathankgusky/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Jennifer Grenier',
    website: null,
    email: 'jenniferagrenier@gmail.com',
    github: 'https://github.com/JAGrenier',
    linkedin: 'https://www.linkedin.com/in/jagrenier/',
    medium: 'https://jagrenier.medium.com/',
    // cohort: '',
  },
  {
    name: 'Phil Haines',
    // website: 'https://www.philiphaines.com/',
    website: 'philiphaines.com',
    email: 'phil.haines92@gmail.com',
    github: 'https://github.com/philip-haines',
    linkedin: 'https://www.linkedin.com/in/philip-haines/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Tara Harwood',
    website: null,
    email: 'tara.m.harwood@gmail.com',
    github: 'https://github.com/tara-m-harwood',
    linkedin: 'https://www.linkedin.com/in/taraharwood/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Grant Hesketh',
    website: null,
    email: 'ghesketh76@gmail.com',
    github: 'https://github.com/ghesketh76',
    linkedin: 'https://www.linkedin.com/in/granthesketh/',
    medium: 'https://ghesketh76.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'John Higger',
    website: null,
    email: null,
    github: 'https://github.com/jjhiggz',
    linkedin: 'https://www.linkedin.com/in/jonathan-higger/',
    medium: 'https://medium.com/@jonathan.higger',
    // cohort: '',
  },
  {
    name: 'Jack Hubert',
    website: null,
    email: 'jphubert93@gmail.com',
    github: 'https://github.com/hydroflux',
    linkedin: 'https://www.linkedin.com/in/jackhubert/',
    medium: null,
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Mary Beth Ingram',
    // website: 'https://www.marybethdev.com/',
    website: 'marybethdev.com',
    email: 'mbingramm@gmail.com',
    github: 'https://github.com/mbingram',
    linkedin: 'https://www.linkedin.com/in/mbingram',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Zachary Jacobs',
    website: null,
    email: 'zprogrammer@icloud.com',
    github: 'https://github.com/zprogrammer-code',
    linkedin: 'https://www.linkedin.com/in/zachary-jacobs-10b3351b5/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Lisa Jung',
    website: null,
    email: 'lisahjung@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/lisahjung/',
    medium: null,
    // dev: 'https://dev.to/lisahjung',
    // twitter: 'https://twitter.com/LisaHJung',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Tiffany Kanjanabout',
    website: null,
    email: null,
    github: 'https://github.com/tiffanynk',
    linkedin: 'https://www.linkedin.com/in/tiffany-kanjanabout/',
    medium: 'https://tiffany-nit-k.medium.com/',
    // cohort: '',
  },
  {
    name: 'Tony Kim',
    // website: 'https://hjkmines.github.io/my-portfolio-website/',
    website: 'hjkmines.github.io/my-portfolio-website',
    email: 'hjkmines@gmail.com',
    github: 'https://github.com/hjkmines',
    linkedin: 'https://www.linkedin.com/in/hyung-kim/',
    medium: 'https://medium.com/@hjkmines',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Austin Kohler',
    website: null,
    email: 'austinckohler@gmail.com',
    github: null,
    linkedin: null,
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Allen Lea',
    website: null,
    email: 'allenlea2007@gmail.com',
    github: 'https://github.com/Allen70',
    linkedin: 'https://www.linkedin.com/in/allen-r-lea/',
    medium: null,
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Louis Leffler',
    website: null,
    email: 'louisleffler@gmail.com',
    github: 'https://github.com/1ouis1effler',
    linkedin: 'https://www.linkedin.com/in/louisleffler/',
    medium: null,
    // cohort: '',
  },
  {
    name: 'Kat Leight',
    website: null,
    email: 'leightkt@gmail.com',
    github: 'https://github.com/leightkt',
    linkedin: 'https://www.linkedin.com/in/kat-leight/',
    medium: 'https://kat-leight.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Phong Lo',
    website: null,
    email: 'phonglo724@gmail.com',
    github: 'https://github.com/phonglo724',
    linkedin: 'https://www.linkedin.com/in/phong-lo',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Matt Long',
    // website: 'https://matt-long.dev/',
    website: 'matt-long.dev',
    email: 'mdlong34@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/mattlong34/',
    medium: 'https://mattlong34.medium.com/',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'JT Lu',
    // website: 'https://jtlu.dev/',
    website: 'jtlu.dev',
    email: 'alohajt94@gmail.com',
    github: 'https://github.com/alohajt',
    linkedin: 'https://www.linkedin.com/in/jt-lu-68917394/',
    medium: 'https://medium.com/@alohajt94',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Denise Magner',
    website: null,
    email: 'deerenae@gmail.com',
    github: 'https://github.com/deerenae',
    linkedin: 'https://www.linkedin.com/in/denise-magner/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Michael Navoy',
    website: null,
    email: 'mnavoy4@gmail.com',
    github: 'https://github.com/mnavoy4',
    linkedin: 'https://www.linkedin.com/in/michael-navoy/',
    medium: 'https://medium.com/@mnavoy4',
    // cohort: 'Run Tie Terrors',
  },
  {
    name: 'William Neal',
    website: null,
    email: 'wln.develops@gmail.com',
    github: 'https://github.com/Jawnny5',
    linkedin: 'https://www.linkedin.com/in/william-neal1283/',
    medium: 'https://wln-develops.medium.com/',
    // william.neal83@gmail.com
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Brett Needham',
    website: null,
    email: 'brettneedham88@gmail.com',
    github: 'https://github.com/brettneedham88',
    linkedin: 'https://www.linkedin.com/in/brettneedham88/',
    medium: 'https://brettneedham88.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Marissa Nolan',
    website: null,
    email: 'ritz1484@cs.com',
    github: 'https://github.com/LittleRedButton7',
    linkedin: 'https://www.linkedin.com/in/marissanolan1/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Adam Nowland',
    // website: 'https://www.adam-nowland.com/',
    website: 'adam-nowland.com',
    email: 'acnowland@gmail.com',
    github: 'https://github.com/acnowland',
    linkedin: 'https://www.linkedin.com/in/adam-nowland/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Obinna Nwabia',
    website: null,
    email: 'valinevite@gmail.com',
    github: 'https://github.com/coremand',
    linkedin: 'https://www.linkedin.com/in/obinna-nwabia-3245b268/',
    medium: null,
    // cohort: 'Hip Hip Arrays',
  },
  {
    name: "Colton O'Connor",
    // website: 'https://coltonoconnor.com/',
    website: 'coltonoconnor.com',
    email: 'colton.shawn.oconnor@gmail.com',
    github: 'https://github.com/bigdumbbaby',
    linkedin: 'https://www.linkedin.com/in/colton-o-connor/',
    medium: 'https://colton-shawn-oconnor.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Bryan Oyloe',
    // website: 'https://bryanoyloe.com/',
    website: 'bryanoyloe.com',
    email: 'boyloe@gmail.com',
    github: 'https://github.com/boyloe',
    linkedin: 'https://www.linkedin.com/in/bryan-oyloe/',
    medium: 'https://medium.com/@bryanoyloe',
    // cohort: '',
  },
  {
    name: 'Kyle Peterson',
    // website: 'https://kylepetersen.dev/',
    website: 'kylepetersen.dev',
    email: 'kpete2017@gmail.com',
    github: 'https://github.com/kpete2017',
    linkedin: 'https://www.linkedin.com/in/kyle-petersen-27259b18b/',
    medium: null,
    // cohort: '',
  },
  {
    name: 'Jessica Pope',
    website: null,
    email: 'jessica.pope.co@gmail.com',
    github: 'https://github.com/JdPope',
    linkedin: 'https://www.linkedin.com/in/jessica-pope-77903033/',
    medium: null,
    // cohort: '',
  },
  {
    name: 'Alison Quaglia',
    website: null,
    email: null,
    github: 'https://github.com/hylobates-lar',
    linkedin: 'https://www.linkedin.com/in/alison-quaglia/',
    medium: 'https://medium.com/@alison.quaglia',
    // codepen: 'https://codepen.io/hylobates-lar',
    // cohort: '',
  },
  {
    name: 'Hailey Ringier',
    website: null,
    email: 'haileyringier@outlook.com',
    github: 'https://github.com/haileyringier',
    linkedin: 'https://www.linkedin.com/in/hailey-ringier/',
    medium: 'https://medium.com/@haileyringier',
    // youtube: 'https://www.youtube.com/channel/UCv8YpacxVgL9ShVduwb3Blg',
    // cohort: 'Run Time Terrors',
  },
  // {
  //   name: 'Summer Rizzo',
  //   website: null,
  //   email: null,
  //   github: null,
  //   linkedin: null,
  //   medium: null,
  //   dev: 'https://dev.to/rizz0s',
  // },
  {
    name: 'Marnie Robinson',
    website: null,
    email: 'marnielane@gmail.com',
    github: 'https://github.com/Marnielane',
    linkedin: 'https://www.linkedin.com/in/marnie-robinson/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Reed Roffis',
    website: null,
    email: 'reedroffis18@gmail.com',
    github: 'https://github.com/reedroffis',
    linkedin: 'https://www.linkedin.com/in/reed-roffis-3a9261110/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Arielle Ross',
    // website: 'https://arielleross.com/',
    website: 'arielleross.com',
    email: 'arielle@arielleross.com',
    github: 'https://github.com/rel-ross',
    linkedin: 'https://www.linkedin.com/in/arielleross/',
    medium: 'https://arielle-10415.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Blake Runyon',
    // website: 'https://kaylinanorton.com/',
    website: 'kaylinanorton.com',
    email: 'blakerunyon09@gmail.com',
    github: 'https://github.com/blakerunyon09',
    linkedin: 'https://www.linkedin.com/in/blakerunyon/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Diana Rybikov',
    website: null,
    email: 'diana.ryb214@gmail.com',
    github: 'https://github.com/dianarybikov',
    linkedin: 'https://www.linkedin.com/in/diana-rybikov-465018202/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Iuliia Saprykina',
    // website: 'https://portfolio-saprykina.firebaseapp.com/',
    website: 'portfolio-saprykina.firebaseapp.com',
    email: 'iuliia.proskurnina@gmail.com',
    github: 'https://github.com/IuliiaSaprykina',
    linkedin: 'https://www.linkedin.com/in/iuliia-saprykina-ab3351100/',
    medium: 'https://iuliia-proskurnina.medium.com/',
    // cohort: '',
  },
  {
    name: 'Alexander Sherwin',
    website: null,
    email: 'alx.sherwin@gmail.com',
    github: 'https://github.com/MomentaiBro',
    linkedin: 'https://www.linkedin.com/in/alexander-sherwin/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Daniel Steed',
    // website: 'https://danielsteed.com/',
    website: 'danielsteed.com',
    email: 'dsteed112@gmail.com',
    github: 'https://github.com/dsteed112',
    linkedin: 'https://www.linkedin.com/in/daniel-steed/',
    medium: 'https://medium.com/@dsteed112',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Jared Stromberg',
    website: null,
    email: null,
    github: 'https://github.com/jstrombe19',
    linkedin: 'https://www.linkedin.com/in/jared-s-122690143/',
    medium: 'https://medium.com/@jaredstromberg',
    // cohort: '',
  },
  {
    name: 'Lucas Thinnes',
    // website: 'https://lucasthinnes.com/',
    website: 'lucasthinnes.com',
    email: 'lukethinnes@protonmail.com',
    github: 'https://github.com/lukethinnes',
    linkedin: 'https://www.linkedin.com/in/lucas-thinnes/',
    medium: 'https://lucasthinnes.medium.com/',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Colter Ulrich',
    website: null,
    email: 'cju5025@gmail.com',
    github: 'https://github.com/cju5025',
    linkedin: 'https://www.linkedin.com/in/colter-ulrich/',
    medium: 'https://cju5025.medium.com/',
    // instagram: 'https://www.instagram.com/colterulrich/',
    // soundcloud: 'https://soundcloud.com/colter-ulrich',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Benton Westergaard',
    website: null,
    email: 'benton.westergaard@gmail.com',
    github: 'https://github.com/bwesterg',
    linkedin: 'https://www.linkedin.com/in/benton-westergaard/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
  {
    name: 'Ashley Winters',
    website: null,
    email: 'ashbwinters@gmail.com',
    github: 'https://github.com/ashbwinters',
    linkedin: 'https://www.linkedin.com/in/ashley-winters/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Blake Woodruff',
    website: null,
    email: 'blakewoodruff4@gmail.com',
    github: 'https://github.com/Bwoodruff4',
    linkedin: 'https://www.linkedin.com/in/blakewoodruffengineer/',
    medium: null,
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Angelo Xenakis',
    // website: 'http://www.angeloxenakis.com/',
    website: 'angeloxenakis.com',
    email: 'evangelosalexander@gmail.com',
    github: 'https://github.com/angeloxenakis/',
    linkedin: 'https://www.linkedin.com/in/angeloxenakis/',
    medium: 'https://medium.com/@angeloxenakis',
    // dribble: 'https://dribbble.com/AngeloTheThird',
  },
  {
    name: 'Steven Yi',
    website: null,
    email: 'stevenliuyi88@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/stevenliuyi/',
    medium: null,
    // cohort: 'Juicy Functions 5/13/21',
  },
];
